taller/config/routes.rb
Rails.application.routes.draw do
  resources :cita
  resources :consultorios
  resources :pacientes
  resources :medicos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

taller/app/models/consultorio.rb
class Consultorio < ApplicationRecord
    validates: nombre, presence:true
    validates: codigo, presence:true
    validates: ubicacion, presence:true
    validates: tipoConsultorio, presence:true
end

taller/app/controllers/consultorios_controller.rb
class ConsultoriosController < ApplicationController
  before_action :set_consultorio, only: [:show, :edit, :update, :destroy]

  # GET /consultorios
  # GET /consultorios.json
  def index
    @consultorios = Consultorio.all
  end

  # GET /consultorios/1
  # GET /consultorios/1.json
  def show
  end

  # GET /consultorios/new
  def new
    @consultorio = Consultorio.new
  end

  # GET /consultorios/1/edit
  def edit
  end

  # POST /consultorios
  # POST /consultorios.json
  def create
    @consultorio = Consultorio.new(consultorio_params)

    respond_to do |format|
      if @consultorio.save
        format.html { redirect_to @consultorio, notice: 'Consultorio was successfully created.' }
        format.json { render :show, status: :created, location: @consultorio }
      else
        format.html { render :new }
        format.json { render json: @consultorio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consultorios/1
  # PATCH/PUT /consultorios/1.json
  def update
    respond_to do |format|
      if @consultorio.update(consultorio_params)
        format.html { redirect_to @consultorio, notice: 'Consultorio was successfully updated.' }
        format.json { render :show, status: :ok, location: @consultorio }
      else
        format.html { render :edit }
        format.json { render json: @consultorio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consultorios/1
  # DELETE /consultorios/1.json
  def destroy
    @consultorio.destroy
    respond_to do |format|
      format.html { redirect_to consultorios_url, notice: 'Consultorio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consultorio
      @consultorio = Consultorio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consultorio_params
      params.require(:consultorio).permit(:nombre, :codigo, :ubicacion, :tipoConsultorio)
    end
end

taller/app/helpers/consultorios_helper.rb
module ConsultoriosHelper
end

taller/app/views/consultorios/_form.html.erb
<%= form_with(model: consultorio, local: true) do |form| %>
  <% if consultorio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(consultorio.errors.count, "error") %> prohibited this consultorio from being saved:</h2>

      <ul>
        <% consultorio.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :codigo %>
    <%= form.number_field :codigo %>
  </div>

  <div class="field">
    <%= form.label :ubicacion %>
    <%= form.text_field :ubicacion %>
  </div>

  <div class="field">
    <%= form.label :tipoConsultorio %>
    <%= form.text_field :tipoConsultorio %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

taller/app/views/consultorios/edit.html.erb
<h1>Editing Consultorio</h1>

<%= render 'form', consultorio: @consultorio %>

<%= link_to 'Show', @consultorio %> |
<%= link_to 'Back', consultorios_path %>

taller/app/views/consultorios/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="text-align: center">Consultorios</h1>

<table border="1" style="margin: 0 auto">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Codigo</th>
      <th>Ubicacion</th>
      <th>Tipoconsultorio</th>
      <th colspan="3">Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @consultorios.each do |consultorio| %>
      <tr>
        <td><%= consultorio.nombre %></td>
        <td><%= consultorio.codigo %></td>
        <td><%= consultorio.ubicacion %></td>
        <td><%= consultorio.tipoConsultorio %></td>
        <td><%= link_to 'Mostrar', consultorio %></td>
        <td><%= link_to 'Editar', edit_consultorio_path(consultorio) %></td>
        <td><%= link_to 'Destruir', consultorio, method: :delete, data: { confirm: '¿Esta Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p style="text-align: center">
<%= link_to 'Nuevo Consultorio', new_consultorio_path %>
</p>

taller/app/views/consultorios/new.html.erb
<h1>New Consultorio</h1>

<%= render 'form', consultorio: @consultorio %>

<%= link_to 'Back', consultorios_path %>

taller/app/views/consultorios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @consultorio.nombre %>
</p>

<p>
  <strong>Codigo:</strong>
  <%= @consultorio.codigo %>
</p>

<p>
  <strong>Ubicacion:</strong>
  <%= @consultorio.ubicacion %>
</p>

<p>
  <strong>Tipoconsultorio:</strong>
  <%= @consultorio.tipoConsultorio %>
</p>

<%= link_to 'Edit', edit_consultorio_path(@consultorio) %> |
<%= link_to 'Back', consultorios_path %>