taller/config/routes.rb
Rails.application.routes.draw do
  resources :cita
  resources :consultorios
  resources :pacientes
  resources :medicos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

taller/app/models/paciente.rb
class Paciente < ApplicationRecord
    validates: nombres, presence:true
    validates: apellidos, presence:true
    validates: fechaNacimiento, presenece:true
    validates: numeroDocumento, presence:true
end

taller/app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_action :set_paciente, only: [:show, :edit, :update, :destroy]

  # GET /pacientes
  # GET /pacientes.json
  def index
    @pacientes = Paciente.all
  end

  # GET /pacientes/1
  # GET /pacientes/1.json
  def show
  end

  # GET /pacientes/new
  def new
    @paciente = Paciente.new
  end

  # GET /pacientes/1/edit
  def edit
  end

  # POST /pacientes
  # POST /pacientes.json
  def create
    @paciente = Paciente.new(paciente_params)

    respond_to do |format|
      if @paciente.save
        format.html { redirect_to @paciente, notice: 'Paciente was successfully created.' }
        format.json { render :show, status: :created, location: @paciente }
      else
        format.html { render :new }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacientes/1
  # PATCH/PUT /pacientes/1.json
  def update
    respond_to do |format|
      if @paciente.update(paciente_params)
        format.html { redirect_to @paciente, notice: 'Paciente was successfully updated.' }
        format.json { render :show, status: :ok, location: @paciente }
      else
        format.html { render :edit }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1
  # DELETE /pacientes/1.json
  def destroy
    @paciente.destroy
    respond_to do |format|
      format.html { redirect_to pacientes_url, notice: 'Paciente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paciente
      @paciente = Paciente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paciente_params
      params.require(:paciente).permit(:nombres, :apellidos, :fechaNacimiento, :numeroDocumento)
    end
end

taller/app/helpers/pacientes_helper.rb
module PacientesHelper
end

taller/app/views/pacientes/_form.html.erb
<%= form_with(model: paciente, local: true) do |form| %>
  <% if paciente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paciente.errors.count, "error") %> prohibited this paciente from being saved:</h2>

      <ul>
        <% paciente.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombres %>
    <%= form.text_field :nombres %>
  </div>

  <div class="field">
    <%= form.label :apellidos %>
    <%= form.text_field :apellidos %>
  </div>

  <div class="field">
    <%= form.label :fechaNacimiento %>
    <%= form.date_select :fechaNacimiento %>
  </div>

  <div class="field">
    <%= form.label :numeroDocumento %>
    <%= form.number_field :numeroDocumento %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

taller/app/views/pacientes/edit.html.erb
<h1>Editing Paciente</h1>

<%= render 'form', paciente: @paciente %>

<%= link_to 'Show', @paciente %> |
<%= link_to 'Back', pacientes_path %>

taller/app/views/pacientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="text-align: center">Pacientes</h1>

<table border="1" style="margin: 0 auto">
  <thead>
    <tr>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Fechanacimiento</th>
      <th>Numerodocumento</th>
      <th colspan="3">Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @pacientes.each do |paciente| %>
      <tr>
        <td><%= paciente.nombres %></td>
        <td><%= paciente.apellidos %></td>
        <td><%= paciente.fechaNacimiento %></td>
        <td><%= paciente.numeroDocumento %></td>
        <td><%= link_to 'Mostrar', paciente %></td>
        <td><%= link_to 'Editar', edit_paciente_path(paciente) %></td>
        <td><%= link_to 'Destruir', paciente, method: :delete, data: { confirm: '¿Estas Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p style="text-align: center">
<%= link_to 'Nuevo Paciente', new_paciente_path %>
</p>

taller/app/views/pacientes/new.html.erb
<h1>New Paciente</h1>

<%= render 'form', paciente: @paciente %>

<%= link_to 'Back', pacientes_path %>

taller/app/views/pacientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombres:</strong>
  <%= @paciente.nombres %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @paciente.apellidos %>
</p>

<p>
  <strong>Fechanacimiento:</strong>
  <%= @paciente.fechaNacimiento %>
</p>

<p>
  <strong>Numerodocumento:</strong>
  <%= @paciente.numeroDocumento %>
</p>

<%= link_to 'Edit', edit_paciente_path(@paciente) %> |
<%= link_to 'Back', pacientes_path %>