taller/config/routes.rb
Rails.application.routes.draw do
  resources :cita
  resources :consultorios
  resources :pacientes
  resources :medicos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

taller/app/controllers/cita_controller.rb
class CitaController < ApplicationController
  before_action :set_citum, only: [:show, :edit, :update, :destroy]

  # GET /cita
  # GET /cita.json
  def index
    @cita = Citum.all
  end

  # GET /cita/1
  # GET /cita/1.json
  def show
  end

  # GET /cita/new
  def new
    @citum = Citum.new
  end

  # GET /cita/1/edit
  def edit
  end

  # POST /cita
  # POST /cita.json
  def create
    @citum = Citum.new(citum_params)

    respond_to do |format|
      if @citum.save
        format.html { redirect_to @citum, notice: 'Citum was successfully created.' }
        format.json { render :show, status: :created, location: @citum }
      else
        format.html { render :new }
        format.json { render json: @citum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cita/1
  # PATCH/PUT /cita/1.json
  def update
    respond_to do |format|
      if @citum.update(citum_params)
        format.html { redirect_to @citum, notice: 'Citum was successfully updated.' }
        format.json { render :show, status: :ok, location: @citum }
      else
        format.html { render :edit }
        format.json { render json: @citum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cita/1
  # DELETE /cita/1.json
  def destroy
    @citum.destroy
    respond_to do |format|
      format.html { redirect_to cita_url, notice: 'Citum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_citum
      @citum = Citum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def citum_params
      params.require(:citum).permit(:consultorio, :paciente, :medico, :fechaCita, :horaInicio, :horaFin, :motivoCita)
    end
end

taller/app/helpers/cita_helper.rb
module CitaHelper
end

taller/app/views/cita/_form.html.erb
<%= form_with(model: citum, local: true) do |form| %>
  <% if citum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(citum.errors.count, "error") %> prohibited this citum from being saved:</h2>

      <ul>
        <% citum.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :consultorio %>
    <%= form.number_field :consultorio %>
  </div>

  <div class="field">
    <%= form.label :paciente %>
    <%= form.number_field :paciente %>
  </div>

  <div class="field">
    <%= form.label :medico %>
    <%= form.number_field :medico %>
  </div>

  <div class="field">
    <%= form.label :fechaCita %>
    <%= form.date_select :fechaCita %>
  </div>

  <div class="field">
    <%= form.label :horaInicio %>
    <%= form.time_select :horaInicio %>
  </div>

  <div class="field">
    <%= form.label :horaFin %>
    <%= form.time_select :horaFin %>
  </div>

  <div class="field">
    <%= form.label :motivoCita %>
    <%= form.text_field :motivoCita %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

taller/app/views/cita/edit.html.erb
<h1>Editing Citum</h1>

<%= render 'form', citum: @citum %>

<%= link_to 'Show', @citum %> |
<%= link_to 'Back', cita_path %>

taller/app/views/cita/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="text-align: center">Cita</h1>

<table border="1" style="margin: 0 auto">
  <thead>
    <tr>
      <th>Consultorio</th>
      <th>Paciente</th>
      <th>Medico</th>
      <th>Fechacita</th>
      <th>Horainicio</th>
      <th>Horafin</th>
      <th>Motivocita</th>
      <th colspan="3">Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @cita.each do |citum| %>
      <tr>
        <td><%= citum.consultorio %></td>
        <td><%= citum.paciente %></td>
        <td><%= citum.medico %></td>
        <td><%= citum.fechaCita %></td>
        <td><%= citum.horaInicio %></td>
        <td><%= citum.horaFin %></td>
        <td><%= citum.motivoCita %></td>
        <td><%= link_to 'Mostrar', citum %></td>
        <td><%= link_to 'Editar', edit_citum_path(citum) %></td>
        <td><%= link_to 'Destruir', citum, method: :delete, data: { confirm: '¿Esta seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p style="text-align: center">
<%= link_to 'Nueva Cita', new_citum_path %>
</p>

taller/app/views/cita/new.html.erb
<h1>New Citum</h1>

<%= render 'form', citum: @citum %>

<%= link_to 'Back', cita_path %>

taller/app/views/cita/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Consultorio:</strong>
  <%= @citum.consultorio %>
</p>

<p>
  <strong>Paciente:</strong>
  <%= @citum.paciente %>
</p>

<p>
  <strong>Medico:</strong>
  <%= @citum.medico %>
</p>

<p>
  <strong>Fechacita:</strong>
  <%= @citum.fechaCita %>
</p>

<p>
  <strong>Horainicio:</strong>
  <%= @citum.horaInicio %>
</p>

<p>
  <strong>Horafin:</strong>
  <%= @citum.horaFin %>
</p>

<p>
  <strong>Motivocita:</strong>
  <%= @citum.motivoCita %>
</p>

<%= link_to 'Edit', edit_citum_path(@citum) %> |
<%= link_to 'Back', cita_path %>