taller/config/routes.rb
Rails.application.routes.draw do
  resources :cita
  resources :consultorios
  resources :pacientes
  resources :medicos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

taller/app/models/medico.rb
class Medico < ApplicationRecord
    validates: nombres, presence:true
    validates: apellidos, presence:true
    validates: numeroIdentificacion, presence:true
    validates: numeroCelular, presence:true
    validates: tipoMedico, presence:true
end

taller/app/controllers/medicos_controller.rb
class MedicosController < ApplicationController
  before_action :set_medico, only: [:show, :edit, :update, :destroy]

  # GET /medicos
  # GET /medicos.json
  def index
    @medicos = Medico.all
  end

  # GET /medicos/1
  # GET /medicos/1.json
  def show
  end

  # GET /medicos/new
  def new
    @medico = Medico.new
  end

  # GET /medicos/1/edit
  def edit
  end

  # POST /medicos
  # POST /medicos.json
  def create
    @medico = Medico.new(medico_params)

    respond_to do |format|
      if @medico.save
        format.html { redirect_to @medico, notice: 'Medico was successfully created.' }
        format.json { render :show, status: :created, location: @medico }
      else
        format.html { render :new }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicos/1
  # PATCH/PUT /medicos/1.json
  def update
    respond_to do |format|
      if @medico.update(medico_params)
        format.html { redirect_to @medico, notice: 'Medico was successfully updated.' }
        format.json { render :show, status: :ok, location: @medico }
      else
        format.html { render :edit }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicos/1
  # DELETE /medicos/1.json
  def destroy
    @medico.destroy
    respond_to do |format|
      format.html { redirect_to medicos_url, notice: 'Medico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medico
      @medico = Medico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medico_params
      params.require(:medico).permit(:nombres, :apellidos, :numeroIdentificacion, :numeroCelular, :tipoMedico)
    end
end

taller/app/helpers/medicos_helper.rb
module MedicosHelper
end

taller/app/views/medicos/_form.html.erb
<%= form_with(model: medico, local: true) do |form| %>
  <% if medico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(medico.errors.count, "error") %> prohibited this medico from being saved:</h2>

      <ul>
        <% medico.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombres %>
    <%= form.text_field :nombres %>
  </div>

  <div class="field">
    <%= form.label :apellidos %>
    <%= form.text_field :apellidos %>
  </div>

  <div class="field">
    <%= form.label :numeroIdentificacion %>
    <%= form.number_field :numeroIdentificacion %>
  </div>

  <div class="field">
    <%= form.label :numeroCelular %>
    <%= form.number_field :numeroCelular %>
  </div>

  <div class="field">
    <%= form.label :tipoMedico %>
    <%= form.text_field :tipoMedico %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

taller/app/views/medicos/edit.html.erb
<h1>Editing Medico</h1>

<%= render 'form', medico: @medico %>

<%= link_to 'Show', @medico %> |
<%= link_to 'Back', medicos_path %>

taller/app/views/medicos/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="text-align: center">Medicos</h1>

<table border="1" style="margin: 0 auto">
  <thead>
    <tr>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Numeroidentificacion</th>
      <th>Numerocelular</th>
      <th>Tipomedico</th>
      <th colspan="3">Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @medicos.each do |medico| %>
      <tr>
        <td><%= medico.nombres %></td>
        <td><%= medico.apellidos %></td>
        <td><%= medico.numeroIdentificacion %></td>
        <td><%= medico.numeroCelular %></td>
        <td><%= medico.tipoMedico %></td>
        <td><%= link_to 'Mostrar', medico %></td>
        <td><%= link_to 'Editar', edit_medico_path(medico) %></td>
        <td><%= link_to 'Destruir', medico, method: :delete, data: { confirm: '¿Esta Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p style="text-align: center">
<%= link_to 'Nuevo Medico', new_medico_path %>
</p>

taller/app/views/medicos/new.html.erb
<h1>New Medico</h1>

<%= render 'form', medico: @medico %>

<%= link_to 'Back', medicos_path %>

taller/app/views/medicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombres:</strong>
  <%= @medico.nombres %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @medico.apellidos %>
</p>

<p>
  <strong>Numeroidentificacion:</strong>
  <%= @medico.numeroIdentificacion %>
</p>

<p>
  <strong>Numerocelular:</strong>
  <%= @medico.numeroCelular %>
</p>

<p>
  <strong>Tipomedico:</strong>
  <%= @medico.tipoMedico %>
</p>

<%= link_to 'Edit', edit_medico_path(@medico) %> |
<%= link_to 'Back', medicos_path %>